deeplearning4j/deeplearning4j-examples

pom.xml

0.4-rc0-SNAPSHOT is better than 0.3.3.3-SNAPTHOT because this depends on
dl4j/nd4j 0.4-rc0.  Symmetric versioning saves users from confusion.

updated misleading artifact version.

---

src/main/java/org/deeplearning4j/examples/deepbelief/DBNMnistFullExample.java

Removed the deprecated config option and replaced it with what (I believe) should provide equivalent functionality. I was able to run the model and have it terminate, though the performance is still dreadful.
Should fix #38

Fix non-termination on DBNMnistFullExample

---

src/main/java/org/deeplearning4j/examples/paragraphvectors/tools/MeansBuilder.java

This removes unused import `org.nd4j.linalg.cpu.NDArray`, which prohibits to switch backend from cpu to others.

remove unused import to avoid depending on cpu backend explicitly

---

.editorconfig

dl4j-examples lacks in my opinion a bit of a common codestyle. This EditorConfig-configuration defines at least some common basics such as UTF8-encoding, indentation style etc. 
[EditorConfig](http://editorconfig.org/) is supposed to define common configurations across different IDEs, editors etc.. GitHub and IntelliJ support EditorConfig by default, for example.

Adding EditorConfig for providing some codestyle-basics.

---

src/main/java/org/deeplearning4j/examples/feedforward/mnist/MLPMnistTwoLayerExample.java

The single-hidden-layer MNIST feedforward/backprop example is pretty limited.  This two-layer example uses more than one hidden layer (ie, is deep) has fewer parameters/weights (therefore smaller in memory and faster to train), uses the same number of epochs (15), and gets only about 20% as many wrong when trained.  
It makes a nice example of the difference in capability between shallow and deep networks.

added a much better 2-layer MNIST feedforward example.

---

src/main/java/org/deeplearning4j/examples/convolution/LenetMnistExample.java

I simply added and set the Boolean parameter for `model.output()` to **false** which invokes "test mode" for scoring rather than the default (**true**).  I'm not sure if it makes a difference for models without dropout, but with dropout, it certainly does.
There's no dropout in this example, however there is in the Scala clone [here](https://github.com/kogecoo/dl4j-0.4-examples-scala/blob/master/src/main/scala/org/deeplearning4j/examples/convolution/LenetMnistExample.scala), which initially threw me off.

changing lenet cnn example to use testmode when scoring test data

---

src/main/java/org/deeplearning4j/examples/nlp/paragraphvectors/ParagraphVectorsTextExample.java

First, I fixed iterations count so that the difference between the last pair and all previous becomes significant (see [here](https://gist.github.com/astrakhantsev/639742481981fe08c0fcc9636b8e364a) for examples of output for iterCount=3). Now the difference is more than 0.1. Also a little more explanation was added. 
Second, I tried to fix the bug with trying to instantiate File from jar entry (see [output](https://gist.github.com/astrakhantsev/cdb29a08e774b0f7b33db77ec5b2c5c7) and relevant [Stackoverflow question](http://stackoverflow.com/questions/14876836/file-inside-jar-is-not-visible-for-spring)). 
I tried to replace resource.getFile() by resource.getInputStream(), but then it fails, because BasicLineIterator tries to read the file twice, and in case of InputStream, it tries to …

Par2vec text fix

---

README.md
runexamples.sh

This script does two things:
* Prompts you for the example to run or lets you run all of them with an invocation flag (`--all`).
* Dynamically determines the list of available examples by search for all programs with `main` routines.
I implemented this because `runallexamples.sh` (which `runexamples.sh` is intended to replace) hard-codes a list of examples, some of which no longer exist. The drawback is that not all examples can be run cleanly without some prior, manual setup. For example, `Word2VecSentimentRNN` requires you to download a large data file and change a hard-coded path within the code.

A new runexamples.sh script to run one or all of the examples

---

runexamples.sh

Indices were being used as if starting at 0 in an elif, when in fact they start at 1. Thus last example didn't run plus when entering 0 another example which shouldn't be run, was run.

Made change to allow last example to be run in runexample.sh.

---

dl4j-examples/src/main/java/org/deeplearning4j/examples/recurrent/character/CharacterIterator.java

The method reset() in CharacterIterator used for GravesLSTMCharModelingExample has the variable nMinibatchesPerEpoch set to the wrong number, so when the example is run with more than 1 epoch an exception is thrown.
The intialization of the offsets was done right in the constructor of CharacterIterator, so I've refactored that out to a new method, which also reset() now uses.
Please let me know if there is anything I could improve or simplify in the fix.

Fix wrong number used in the reset method of CharacterIterator

---

dl4j-cuda-specific-examples/pom.xml
dl4j-examples/pom.xml

This makes it easier for people to switch the backend to cuda-8.0.

Add nd4j-cuda-8.0-platform to dependencyManagement.

---

dl4j-examples/pom.xml
pom.xml

`mvn install` fails without explicit jcommons dependency

Add jcommons dependency

---

dl4j-examples/src/main/java/org/deeplearning4j/examples/feedforward/classification/PlotUtil.java

It does not matter for the 3 classification examples. But the correct function to use is IMax to look for maximum value. Not IAMax which looks for the max _absolute_ value.

Change plotutils to use IMax  not IAMax

---

dl4j-examples/src/main/java/org/deeplearning4j/examples/recurrent/video/VideoClassificationExample.java

When evaluating the time series, line 196 reads
evaluation.evalTimeSeries(predicted, actual);
Changed now to
evaluation.evalTimeSeries(actual, predicted);

Fix evalTimeSeries argument order

---

dl4j-examples/src/main/java/org/deeplearning4j/examples/feedforward/classification/detectgender/PredictGenderTrain.java

I thought someone at DL4J would like to know: The PredictGenderTrain dl4j example frequently does not learn/converge (~50% error through all epochs). It seems to work reliably when I reduce the learningRate = 0.005;//GF was .01 
So, you might update source code.
Adam Gibson told me to let you know as a Pull Request instead of Gitter Chat.  I think he's a busy guy.

PredictGenderTrain.java  frequently didn't converge.  Decreasing learning rate solved it for me.

---

dl4j-examples/src/main/java/org/deeplearning4j/examples/dataExamples/ImageDrawer.java

Example uses Javafx, hence requires Oracle JDK.
#2608

Update Javadoc comment.

---

dl4j-examples/src/main/java/org/deeplearning4j/examples/recurrent/regression/MultiTimestepRegressionExample.java

Do to a bug in how the data sets where loaded in MultiTimestepRegressionExample.java, the test data set and train data set had overlap. This makes them both unique.

Updated RNN Multistep Regression Model Data Loading

---

dl4j-examples/src/main/java/org/deeplearning4j/examples/recurrent/character/GravesLSTMCharModellingExample.java

In the GravesLSTMCharModellingExample class, the sampleFromDistribution method was assuming that its input distribution would sum to 1. However, rounding error means that this is not guaranteed to be the case. I had the demo crash because the randomly chosen number was 0.99999993, but the sum was only 0.99999985.
Fix this issue by having sampleFromDistribution try up to 10 times.
I hereby release this contribution under the Apache License, Version 2.0.

Fix issue with sampleFromDistribution

---

dl4j-cuda-specific-examples/pom.xml

You can see the dependencies that were duplicated adjacent to the ones that were removed. This prevented mvn clean install from working for me, due to the linter you have installed here: https://github.com/deeplearning4j/dl4j-examples/blob/master/pom.xml#L98

Remove duplicated dependencies from dl4j-cuda-specific-examples/pom.xml

---

README.md
dl4j-examples/src/main/java/org/deeplearning4j/examples/userInterface/GradientsListenerExample.java
dl4j-examples/src/main/java/org/deeplearning4j/examples/userInterface/util/GradientsListener.java
dl4j-examples/src/main/java/org/deeplearning4j/examples/userInterface/util/GradientsViewer.java

GradientsListener extends TrainingListener and calls GradientsViewer to do
the visualization. GradientsListener should work with any MultiLayerNetwork.
GradientsListenerExample is a demo.

A listener for visualizing gradients in real time in 3D using JavaFX.

---

dl4j-examples/src/main/java/org/deeplearning4j/examples/dataexamples/ImagePipelineExample.java

Remove unused variable (numexamples)
Moved the outputNum from hard-coded to be read from the recordreader.
(The hard coded 4 was wrong: example has 3 labels)
Manually checked that the example runs.
Please review

Remove unused variable - Move hard coded variable.

---

dl4j-examples/src/main/java/org/deeplearning4j/examples/recurrent/seq2seq/AdditionRNN.java

Within the AdditionRNN class, I moved the epoch counter so that when an epoch completes, it refers to the right one.

Increment epoch counter after epoch complete output for AdditionRNN example

---

dl4j-examples/src/main/java/org/deeplearning4j/examples/feedforward/anomalydetection/VaeMNISTAnomaly.java
dl4j-examples/src/main/java/org/deeplearning4j/examples/feedforward/classification/detectgender/GenderRecordReader.java
dl4j-examples/src/main/java/org/deeplearning4j/examples/misc/centerloss/CenterLossLenetMnistExample.java
dl4j-examples/src/main/java/org/deeplearning4j/examples/misc/customlayers/layer/CustomLayerImpl.java
dl4j-examples/src/main/java/org/deeplearning4j/examples/misc/externalerrors/MultiLayerNetworkExternalErrors.java
dl4j-examples/src/main/java/org/deeplearning4j/examples/nlp/paragraphvectors/ParagraphVectorsClassifierExample.java
dl4j-examples/src/main/java/org/deeplearning4j/examples/nlp/paragraphvectors/tools/LabelSeeker.java
dl4j-examples/src/main/java/org/deeplearning4j/examples/nlp/tsne/TSNEStandardExample.java
dl4j-examples/src/main/java/org/deeplearning4j/examples/recurrent/seqclassification/UCISequenceClassificationExample.java
dl4j-examples/src/main/java/org/deeplearning4j/examples/unsupervised/variational/plot/PlotUtil.java
lstm-hdfs/src/main/java/org/deeplearning4j/examples/StackSequenceRecordReader.java

See also deeplearning4j/deeplearning4j@4e42213
and al.
[Merge only just before triggering the release build : since the berkeley removal is published to 0.9.x-SNAPSHOT, this will only build if dependencies are replaced by some 0.9.x, which the release will do]
[also this depends on numerous 0.9.x-SNAPSHOT adaptations PRs]

Helps the removal of berkeley.Pair (do not merge)

---

.gitignore

Added a .gitignore entry for the .settings folder that eclipse generates when importing as a project
Build still passes, but other than that I don't see much need for specific testing of a small .gitignore update :-)

Added eclipse's .settings folder to .gitignore

---

dl4j-cuda-specific-examples/pom.xml
dl4j-cuda-specific-examples/src/main/java/org/deeplearning4j/examples/multigpu/vgg16/dataHelpers/FeaturizedPreSave.java
dl4j-cuda-specific-examples/src/main/java/org/deeplearning4j/examples/multigpu/vgg16/dataHelpers/FlowerDataSetIterator.java
dl4j-cuda-specific-examples/src/main/java/org/deeplearning4j/examples/multigpu/vgg16/vgg16/FitFromFeaturized.java
dl4j-examples/src/main/java/org/deeplearning4j/examples/transferlearning/vgg16/dataHelpers/FlowerDataSetIterator.java
dl4j-spark-examples/dl4j-spark/src/main/java/org/deeplearning4j/transferlearning/vgg16/FitFromFeaturized.java
dl4j-spark-examples/dl4j-spark/src/main/java/org/deeplearning4j/transferlearning/vgg16/dataHelpers/FeaturizedPreSave.java
dl4j-spark-examples/dl4j-spark/src/main/java/org/deeplearning4j/transferlearning/vgg16/dataHelpers/FlowerDataSetIterator.java
dl4j-spark-examples/pom.xml

Updated deprecated code across all examples directories.
One deprecated line form dl4j-examples slipped through.
resolves #524
Everything run manually in dl4j-examples. 'It compiled' for the other directories.

Updated deprecated code across all examples directories.

---

dl4j-cuda-specific-examples/pom.xml

dl4j-examples mvn clean install terminates due to eror in dl4j-cuda-specific-example pom.xml
I just removed the content because it is duplicated, below, from pom.xml and it is resolved :
```
<dependency> 
<groupId>org.deeplearning4j</groupId> 
<artifactId>deeplearning4j-zoo</artifactId> 
<version>${dl4j.version}</version> 
</dependency> 
```
manually tested
```
[INFO] Reactor Summary:
[INFO]
[INFO] DeepLearning4j Examples Parent ..................... SUCCESS [ 11.232 s]
[INFO] DeepLearning4j Examples ............................ SUCCESS [02:38 min]
[INFO] dl4j-spark-examples ................................ SUCCESS [  0.409 s]
[INFO] dl4j-spark ......................................... SUCCESS [01:48 min]
[INFO] datavec-examples ................................... SUCCESS [ 24.655 s] …
```

dl4j-examples : mvn clean install terminates due to eror in dl4j-cuda-specific-example pom.xml

---

dl4j-examples/src/main/java/org/deeplearning4j/examples/recurrent/word2vecsentiment/SentimentExampleIterator.java
dl4j-examples/src/main/java/org/deeplearning4j/examples/recurrent/word2vecsentiment/Word2VecSentimentRNN.java

This patch vectorizes the feature generation in the `SentimentExampleIterator` to improve the performance and show how to generate features in a vectorized manner instead of element-wise.
This change patch was tested with [this gist](https://gist.github.com/slang03/11951b2f5e6fc35ab84fee3d2e37dc2a).
To ensure there is an actual performance improvement, [this gist](https://gist.github.com/slang03/ba4695dc0ae28f51f557bd711ccc746e) was run, comparing element-wise wordvector feature generation with the vectorized version. Both versions were run 100 times for batch sizes in `[2^4, ..., 2^9]`. On average the vectorized version was ~ 2-3 times faster than the elementwise. Results may vary on different machines.

Vectorize wordvector generation

---

dl4j-examples/src/main/java/org/deeplearning4j/examples/nlp/word2vec/Word2VecRawTextExample.java
dl4j-examples/src/main/java/org/deeplearning4j/examples/nlp/word2vec/Word2VecUptrainingExample.java

In W2V examples it seems that using 'wordsNearestSum' instead of 'wordsNearest' gives slightly better results:
- wordsNearest: [night, week, game, year, season, group, time, office, program, set]
- wordsNearestSum: [day, week, night, year, game, season, time, years, while, two]   
I have also successfully tried this with the [Billboard HOT100 dataset](http://kaylinwalker.com/50-years-of-pop-music).
Manual test running the examples 51 and 52.

better results with 'nearestSum' in W2V examples

---

dl4j-examples/src/main/java/org/deeplearning4j/examples/dataexamples/ImageDrawer.java

Old version would hang after the window was closed. We now System.exit the application.
Verified the sample still runs manually.

Sample now shuts down correctly. Harshly but it shuts down.

---

dl4j-examples/src/main/java/org/deeplearning4j/examples/convolution/mnist/MnistClassifier.java
dl4j-examples/src/main/java/org/deeplearning4j/examples/convolution/mnist/MnistClassifierUI.java
dl4j-examples/src/main/java/org/deeplearning4j/examples/dataexamples/MnistImagePipelineExample.java
dl4j-examples/src/main/java/org/deeplearning4j/examples/dataexamples/MnistImagePipelineExampleAddNeuralNet.java
dl4j-examples/src/main/java/org/deeplearning4j/examples/dataexamples/MnistImagePipelineExampleLoad.java
dl4j-examples/src/main/java/org/deeplearning4j/examples/dataexamples/MnistImagePipelineExampleSave.java
dl4j-examples/src/main/java/org/deeplearning4j/examples/dataexamples/MnistImagePipelineLoadChooser.java
dl4j-examples/src/main/java/org/deeplearning4j/examples/utilities/DataUtilities.java

I'm basically merging `MnistImagePipelineExample` and `LenetMnistExample` with some hyperparameters tuning to achieve 99% accuracy. 
I have also done some cleanup to the existing code.
I would like to thank @jesuino for his nice JavaFX test console.
```
o.n.l.f.Nd4jBackend - Loaded [CpuBackend] backend
o.n.n.NativeOpsHolder - Number of threads used for NativeOps: 2
o.n.n.Nd4jBlas - Number of threads used for BLAS: 2
o.n.l.a.o.e.DefaultOpExecutioner - Backend used: [CPU]; OS: [Windows 7]
o.n.l.a.o.e.DefaultOpExecutioner - Cores: [4]; Memory: [1,7GB];
o.n.l.a.o.e.DefaultOpExecutioner - Blas vendor: [OPENBLAS]
```
- Accuracy: 0,9906
- Precision: 0,9905
- Recall: 0,9905
- F1 Score: 0,9905
Manual test on all touched examples using `runexamples.sh`:
5. MnistClassifier
6. MnistClassifierUI
14. …

MnistClassifier example with 99% accuracy and test console

---

dl4j-examples/src/main/java/org/deeplearning4j/examples/convolution/mnist/MnistClassifier.java

Further improvement on MNIST Classifier's accuracy: from 0,9906 to 0,9910.
Changes:
- small changes in learning rate schedule
- switch from l2 to l1 regularization
Result:
- Accuracy: 0,9910
- Precision: 0,9910
- Recall: 0,9909
- F1 Score: 0,9909
Manual test with `runexamples.sh` script.

further improvement on mnist classifier

---

README.md

Added `openjfx` to the `apt-get` command to install in Ubuntu in the README, as that was needed to build the examples on my system.

Adding to OpenJFX installation command for Ubuntu.

---

dl4j-spark-examples/dl4j-spark/src/main/java/org/deeplearning4j/mlp/MnistMLPDistributedExample.java

AFAICT the MnistMLPDistributedExample is currently using the training set as a testing set.
Manual

MnistMLPDistributedExample should use the actual mnist test set

---

datavec-examples/src/main/java/org/datavec/inputsplit/Ex02_CollectionSplitExample.java

This is in reference to a minor change where "jpg" is changed to ".jpg".
Other InputSplit examples followed the same approach. Updated accordingly to avoid any confusion and to follow more intuitive approach.
Only 1 file has changed: "Ex02_CollectionSplitExample.java"
Manual test was performed. Here is the snapshot for results without any error.
Please review

minor fix : changed jpg to .jpg for more intuition + comments added

---

dl4j-examples/src/main/java/org/deeplearning4j/examples/convolution/captcharecognition/MultiRecordDataSetIterator.java
dl4j-examples/src/main/java/org/deeplearning4j/examples/recurrent/character/melodl4j/Note.java
dl4j-examples/src/main/java/org/deeplearning4j/examples/recurrent/encdec/EncoderDecoderLSTM.java
dl4j-examples/src/main/java/org/deeplearning4j/examples/recurrent/processlottery/LotteryCombinationDataSetReader.java
dl4j-spark-examples/dl4j-spark/src/main/java/org/deeplearning4j/patent/preprocessing/JSoupXmlParser.java

I work for Semmle, the company behind LGTM. I noticed some alerts that were raised during LGTM analysis of dl4j-examples, and fixed some of them. Specifically,
- `Self assignment` in MultiRecordDataSetIterator
- `Type mismatch on container access` in EncoderDecoderLSTM
- `Missing format argument` in JSoupXmlParser
- `Dereferenced variable is always null` in LotteryCombinationDataSetReader
- `Hashed value without hashCode definition` in MidiMusicExtractor and MidiMelodyExtractor (fixed by defining hashCode in Note)
- `Reference equality check on boxed types` in Note
- `Equals does not inspect argument type` in Note
- `Inconsistent equals and hashCode` in Note

fix some LGTM alerts

---

dl4j-examples/src/main/java/org/deeplearning4j/examples/recurrent/word2vecsentiment/SentimentExampleIterator.java
dl4j-examples/src/main/java/org/deeplearning4j/examples/recurrent/word2vecsentiment/Word2VecSentimentRNN.java

- Fix a bug in the `Word2VecSentimentRNN` example when predicting short reviews.
- Run the main method in `Word2VecSentimentRNN` with test review `neg/12100_1.txt`:
```
Hated it with all my being. Worst movie ever. Mentally- scarred. Help me. It was that bad.TRUST ME!!!
```
- Before the patch we obtain:
```
Probabilities at last time step:
p(positive): 0.5197249054908752
p(negative): 0.48027509450912476
```
- After the patch we obtain:
```
Probabilities at last time step:
p(positive): 0.08360758423805237
p(negative): 0.91639244556427
```

[Word2VecSentimentRNN] Fix a bug when predicting short reviews (fixes #761)

---

dl4j-examples/src/main/java/org/deeplearning4j/examples/arbiter/genetic/BaseGeneticHyperparameterOptimizationExample.java
dl4j-examples/src/main/java/org/deeplearning4j/examples/arbiter/genetic/CustomGeneticHyperparameterOptimizationExample.java
dl4j-examples/src/main/java/org/deeplearning4j/examples/arbiter/genetic/GeneticSearchExampleConfiguration.java

I added 2 examples demonstrating how to use the GeneticSearchCandidateGenerator. The first one is the basic way to use it with all default settings. The other one is more complex and overrides several behaviors.
Note : Currently, these examples need the SNAPSHOT builds.

Arbiter : added two genetic hyperparameter optimization examples

---

dl4j-examples/src/main/java/org/deeplearning4j/examples/convolution/objectdetection/HouseNumberDetection.java

Signed-off-by: yptheangel <choowilson93@gmail.com>
Added the feature to draw bounding boxes and label text in different colours to show different classes. This is a new PR as the older PR was not signed-off to fit Eclipse PR criteria
This patch was manually tested on  Win10, 1.0.0-beta5

Draw Bbox and label text in diff colours

---

android/DL4JImageRecognitionDemo/app/build.gradle
android/DL4JImageRecognitionDemo/build.gradle
android/DL4JIrisClassifierDemo/app/build.gradle
android/DL4JIrisClassifierDemo/app/src/main/java/org/deeplearning4j/examples/iris_classifier/MainActivity.java
android/DL4JIrisClassifierDemo/build.gradle

Signed-off-by: yptheangel <choowilson93@gmail.com>
project gradle: update gradle version from 3.0.1 to 3.4.2.
app gradle: change "compile" to "implementation" as "compile" is deprecated.
Tested on a forked repo, https://github.com/yptheangel/dl4j-examples

Update project and app gradle files for android

---

data-pipeline-examples/pom.xml
dl4j-examples/pom.xml
nd4j-ndarray-examples/pom.xml
rl4j-examples/pom.xml
samediff-examples/pom.xml
tensorflow-keras-import-examples/pom.xml

Removed duplicated plugin declaration (maven-compiler-plugin) in pom files.
Build all packages after changes.
Please review

Maven duplicated plugin

---

dl4j-examples/src/main/java/org/deeplearning4j/examples/quickstart/modeling/feedforward/unsupervised/MNISTAutoencoder.java

SOFTMAX default does not work with autoencoders.
Fix broken MNISTAutoencoder example.
Visually tested.
Please review

Fix MNISTAutoencoder: switch output layer to LEAKYRELU

---

dl4j-examples/src/main/java/org/deeplearning4j/examples/advanced/modelling/charmodelling/melodl4j/MelodyModelingExample.java
dl4j-examples/src/main/java/org/deeplearning4j/examples/advanced/modelling/charmodelling/melodl4j/MidiScoreIterationListener.java
dl4j-examples/src/main/java/org/deeplearning4j/examples/advanced/modelling/charmodelling/melodl4j/PlayMelodyStrings.java

Support turning off truncated backpropagation. Print out configuration info to stdout and to composition output file (in comments). Use JFileChooser in PlayMelodyStrings. Improve documentation. Clean up code.
Support turning off truncated backpropagation by setting tbpttLength=0.
Print out configuration information as a comment in the output composition file and to stdout. (This helps with benchmarking.)
Use JFileChooser in PlayMelodyStrings to choose the file to play melodies from. By default it uses the directory where MelodyModelingExample saves compositions.
Improve documentation. Clean up code.
I ran MelodyModelingExample several times, with tbpttLength=0 and tbpttLength>0.  I verified that composition files appear in the expected location.
Please review …

Support turning off truncated backpropagation. Other minor fixes.

---

dl4j-examples/src/main/java/org/deeplearning4j/examples/advanced/modelling/charmodelling/melodl4j/TestMelodyConversion.java

I'm sorry,  There was a three-character typo in a method name in TestMelodyConversion.java that causes a compilation exception.
Re-ran MelodyModelingExample and TestMelodyConverstion.
Please review

Fix typo in method name that would cause compilation failure
