src/main/java/org.deeplearning4j.examples/tsne/TSNEStandardExample.java
We should create output directories first for the output file.
=> Fix FileNotFoundException in TSNEStandardExample.

src/main/java/org/deeplearning4j/examples/rnn/CharacterIterator.java, src/main/java/org/deeplearning4j/examples/rnn/GravesLSTMCharModellingExample.java
*** HOLD OFF MERGING ***
Added GravesLSTM character modelling example (Shakespeare)
Notes:
- Won't run/compile on current examples (0.4-rc0 in pom) due to requiring RNN features added to master after 0.4-rc0 was released. Runs OK on master and hence will be OK when 0.4-rc1 is released
- Not tuned
- Running currently to ensure it does something vaguely sensible with current hyperparameters
=> Add GravesLSTM character modelling example

src/main/java/org/deeplearning4j/examples/convolution/CNNIrisExample.java, src/main/java/org/deeplearning4j/examples/convolution/CNNLFWExample.java, src/main/java/org/deeplearning4j/examples/convolution/CNNMnistExample.java
Renamed to match other examples. Added variable calls back into CNN
=> Added eval and train test split to LFW. 

src/main/java/org/deeplearning4j/examples/convolution/LenetMnistExample.java
***DO NOT MERGE UNTIL DL4J-0.4rc3.8 IS RELEASED***
Example utilizes changes to MnistDataSetIterator that are not present in 0.4-rc3.7 or earlier.
Significantly improves accuracy on example. 97.17% accuracy after 5 iterations, 97.62% after 10. Could further improve with learning rate decay.
=> LenetMnistExample tuning

pom.xml, src/main/java/org/deeplearning4j/examples/convolution/CNNLFWExample.java, src/main/java/org/deeplearning4j/examples/convolution/LenetMnistExample.java
=> Updated LFW example - gets f1 scores now

pom.xml, src/main/java/org/deeplearning4j/examples/abstractvectors/AbstractVectorsTextExample.java, src/main/java/org/deeplearning4j/examples/glove/GloVeExample.java, src/main/java/org/deeplearning4j/examples/paragraphvectors/ParagraphVectorsTextExample.java, src/main/java/org/deeplearning4j/examples/sequencevectors/SequenceVectorsTextExample.java, src/main/java/org/deeplearning4j/examples/word2vec/Word2VecRawTextExample.java, src/main/java/org/deeplearning4j/examples/word2vec/Word2VecUptrainingExample.java
**DO NOT MERGE BEFORE DL4J/ND4J rc3.8 IS RELEASED**
- AbstractVectors example
- ParagraphVectors example
=> 2 new examples

src/main/java/org/deeplearning4j/examples/word2vec/sentiment/SentimentExampleIterator.java, src/main/java/org/deeplearning4j/examples/word2vec/sentiment/Word2VecSentimentRNN.java
***DO NOT MERGE UNTIL DL4J/ND4J 0.4-rc3.8 IS RELEASED***
Relies on new features (masking + variable length time series etc) so won't work for 0.4-rc3.7 or earlier.
=> Add Word2Vec sentiment example

src/main/java/org/deeplearning4j/examples/deepbelief/DBNIrisExample.java
=> dropout verification

src/main/java/org/deeplearning4j/examples/convolution/CNNIrisExample.java, src/main/java/org/deeplearning4j/examples/convolution/Cifar.java, src/main/java/org/deeplearning4j/examples/earlystopping/EarlyStoppingMNIST.java, src/main/java/org/deeplearning4j/examples/paragraphvectors/tools/FileLabelAwareIterator.java, src/main/java/org/deeplearning4j/examples/test/Test.java, src/main/java/org/deeplearning4j/examples/word2vec/sentiment/Word2VecSentimentRNN.java
This pull request is focused on resolving occurrences of Sonar rules 
squid:S1481 Unused local variables should be removed.
squid:S1854 Dead stores should be removed.
You can find more information about the issues here:
https://dev.eclipse.org/sonar/coding_rules#q=squid%3AS1481
https://dev.eclipse.org/sonar/coding_rules#q=squid%3AS1854
Please let me know if you have any questions.
George Kankava
=> Multiple code improvements: squid:S1481, squid:S1854

pom.xml, src/main/java/org/deeplearning4j/examples/feedforward/regression/RegressionMathFunctions.java, src/main/java/org/deeplearning4j/examples/feedforward/regression/RegressionSum.java
Add neural net to learn the addition function.
It can easily be expanded to learn more functions, also maybe my way of working with ND4J arrays is not the best and I would love it if someone could improve on it. 
Regression example with multiple multi col input.
=> NeuralNet example for implementing addition function

src/main/java/org/deeplearning4j/examples/feedforward/regression/RegressionMathFunctions.java, src/main/java/org/deeplearning4j/examples/feedforward/regression/function/MathFunction.java, src/main/java/org/deeplearning4j/examples/feedforward/regression/function/SawtoothMathFunction.java, src/main/java/org/deeplearning4j/examples/feedforward/regression/function/SinMathFunction.java, src/main/java/org/deeplearning4j/examples/feedforward/regression/function/SinXDivXMathFunction.java, src/main/java/org/deeplearning4j/examples/feedforward/regression/function/SquareWaveMathFunction.java, src/main/java/org/deeplearning4j/examples/feedforward/regression/function/TriangleWaveMathFunction.java
I added an example of how to use a network configuration using GravesLSTM-layers. On the road, I refactored MathFunctions out of RegressionMathFunctions for better reusage and having RegressionMathFunctions more clearly.
=> Adding a network configuration using  GravesLSTM-layers as math regression example

pom.xml
In my opinion pom.xml needed some love:
- Extracted all library-versions to properties-variables.
- Minimum maven is now defined, as 3.0.5
- Removed jackson-dataformat-yaml, unused?!
- maven-shade-plugin was outdated, updated from 1.6 to 2.4.3
=> Updating_pom_libraries

src/main/java/org/deeplearning4j/examples/xor/XorExample.java
i've added an example how to train a network with an xor DataSet and tried to comment every line
=> added basic xor example

src/main/java/org/deeplearning4j/examples/convolution/LenetMnistExample.java
Using a network similar to the Caffe example. Please merge if this looks alright.
=> Increase accuracy of LenetMnistExample to > 0.99

src/main/java/org/deeplearning4j/examples/recurrent/basic/BasicRNNExample.java
added a basic rnn example with comments
=> BasicRNNExample

src/main/java/org/deeplearning4j/examples/nlp/paragraphvectors/ParagraphVectorsClassifierExample.java, src/main/java/org/deeplearning4j/examples/nlp/paragraphvectors/tools/LabelSeeker.java, src/main/java/org/deeplearning4j/examples/nlp/paragraphvectors/tools/MeansBuilder.java, src/main/java/org/deeplearning4j/examples/nlp/word2vec/Word2VecUptrainingExample.java
changes in comments: line feeds
=> refactor ParagraphVectorsClassifierExample: split main() into 2 methods

src/main/resources/dropwizard.yml
https://gitter.im/deeplearning4j/deeplearning4j?at=576a692d0ede04dc4903a9c5
=> Fixes "Unrecognized field at: template" error

dl4j-examples/src/main/java/org/deeplearning4j/examples/convolution/LenetMnistExample.java
https://github.com/deeplearning4j/deeplearning4j/issues/1403
=> Doc for conv nin/nout clarification

dl4j-examples/pom.xml, pom.xml
Downloads automatically binaries for all platforms
=> Depend on nd4j-native-platform and nd4j-cuda-7.5-platform artifacts

dl4j-examples/src/main/java/org/deeplearning4j/examples/dataExamples/CSVPlotter.java
Read xy data from a csv file. Plot the data, fit the data, plot the data
+ fit.
Hope this is what you had in mind for this issue.
=> complete CSV Example for #151

dl4j-examples/src/main/java/org/deeplearning4j/examples/recurrent/character/CharacterIterator.java, dl4j-examples/src/main/java/org/deeplearning4j/examples/recurrent/seq2seq/CustomSequenceIterator.java, dl4j-examples/src/main/java/org/deeplearning4j/examples/recurrent/word2vecsentiment/SentimentExampleIterator.java, pom.xml
Merge after the release of version 0.5.0
=> Update to version 0.5.0

dl4j-examples/src/main/java/org/deeplearning4j/examples/dataExamples/CSVPlotter.java
Tested from Eclipse and mvn command line.
=> Fix path. (Hopefully for the last time)

dl4j-examples/src/main/java/org/deeplearning4j/examples/dataExamples/CSVPlotter.java
As in the title. IntelliJ found a few issues.
=> IntelliJ Code analysis corrections.

dl4j-examples/src/main/java/org/deeplearning4j/examples/feedforward/classification/MLPClassifierSaturn.java
Using ClassPathResource from nd4j.
=> make example run from maven command line.

datavec-examples/src/main/java/org/datavec/transform/basic/BasicDataVecExample.java
Just for loading data there is a simpler example, so add a reference to it.
=> Add a note that there is a simpler example

dl4j-examples/src/main/java/org/deeplearning4j/examples/convolution/LenetMnistExample.java
Updated documentation to make it a bit easier on newcomers
=> Updated documentation

dl4j-examples/src/main/java/org/deeplearning4j/examples/feedforward/mnist/MLPMnistSingleLayerExample.java
Added inline documentation and file description to the most basic MNIST classification example.
This should help any beginners understand what is going on in this file.
=> Updated inline documentation of MLPMnistSingleLayerExample.java

dl4j-examples/src/main/java/org/deeplearning4j/examples/feedforward/regression/function/SinMathFunction.java, dl4j-examples/src/main/java/org/deeplearning4j/examples/feedforward/regression/function/SinXDivXMathFunction.java, dl4j-examples/src/main/java/org/deeplearning4j/examples/feedforward/regression/function/SquareWaveMathFunction.java
SinMathFunction
SinXDivXMathFunction
SquareWaveMathFunction
=> Documentation Added For Several Files

dl4j-examples/src/main/java/org/deeplearning4j/examples/nlp/word2vec/Word2VecRawTextExample.java
Also, changed one System.out.print line to include a bit of information about what it is printing.
=> Added Documentation to Word2VecRawTextExample.java

dl4j-examples/src/main/java/org/deeplearning4j/examples/recurrent/word2vecsentiment/Word2VecSentimentRNN.java
**_DO NOT MERGE BEFORE NEXT RELEASE**_
use staticWord2Vec in sentimentRNN example, to make it more suitable on GPU systems
=> NEXT RELEASE MERGE: off-gpu Word2Vec model for RNN example

dl4j-examples/src/main/java/org/deeplearning4j/examples/dataExamples/MnistImagePipelineExample.java, dl4j-examples/src/main/java/org/deeplearning4j/examples/dataExamples/MnistImagePipelineExampleAddNeuralNet.java, dl4j-examples/src/main/java/org/deeplearning4j/examples/dataExamples/MnistImagePipelineExampleLoad.java, dl4j-examples/src/main/java/org/deeplearning4j/examples/dataExamples/MnistImagePipelineExampleSave.java, dl4j-examples/src/main/java/org/deeplearning4j/examples/dataExamples/MnistImagePipelineLoadChooser.java
Add 5 examples from the video tutorials,
=> Files from videos

dl4j-examples/src/main/java/org/deeplearning4j/examples/misc/presave/LoadPreSavedLenetMnistExample.java, dl4j-examples/src/main/java/org/deeplearning4j/examples/misc/presave/PreSave.java
Add pre save example.  Pre saving datasets is crucial for speed.
=> add example for async iterator and pre saving data

dl4j-examples/src/main/java/org/deeplearning4j/examples/nlp/word2vec/Word2VecUptrainingExample.java
change the class for LoggerFactory
=> change the class for LoggerFactory

dl4j-examples/src/main/java/org/deeplearning4j/examples/feedforward/classification/detectgender/GenderRecordReader.java
It was causing compilation failures on my system. It was probably imported by
IDE autocompletion?
Use org.deeplearning4j.berkeley.Pair which seems more widely used in this
project.
=> Do not use javafx.util.Pair

dl4j-examples/src/main/java/org/deeplearning4j/examples/unsupervised/deepbelief/DeepAutoEncoderExample.java
RMSE_XENT  is Deprecated, and may cause "UnsupportedOperationException".
=> change LossFunction

dl4j-examples/src/main/java/org/deeplearning4j/examples/misc/activationfunctions/CustomActivation.java, dl4j-examples/src/main/java/org/deeplearning4j/examples/misc/activationfunctions/CustomActivationExample.java
*DO NOT MERGE UNTIL NEXT RELEASE*
=> Custom activation function example

dl4j-examples/src/main/java/org/deeplearning4j/examples/recurrent/word2vecsentiment/SentimentExampleIterator.java, dl4j-examples/src/main/java/org/deeplearning4j/examples/recurrent/word2vecsentiment/Word2VecSentimentRNN.java, dl4j-examples/src/main/java/org/deeplearning4j/examples/userInterface/UIExample.java, pom.xml
***WIP DO NOT MERGE***
Improvements to sentiment example.
- Use static w2v model (keeps w2v data off GPU, if using GPU backend)
- Improvements (probably - needs further validation) to tuning
- Adds post training methods + example
=> Improvements to W2V sentiment example

nd4j-examples/src/main/java/org/nd4j/examples/Nd4jEx10_ElementWiseOperation.java, nd4j-examples/src/main/java/org/nd4j/examples/Nd4jEx11_Axpy.java, nd4j-examples/src/main/java/org/nd4j/examples/Nd4jEx12_INDArrayFromCSCMatrix.java, nd4j-examples/src/main/java/org/nd4j/examples/Nd4jEx13_LargeMatrices.java, nd4j-examples/src/main/java/org/nd4j/examples/Nd4jEx7_MatrixOperation.java, nd4j-examples/src/main/java/org/nd4j/examples/Nd4jEx8_ReshapeOperation.java, nd4j-examples/src/main/java/org/nd4j/examples/Nd4jEx9_Functions.java
* Move existing examples from nd4j-examples into this repo
* Add a new example for creating an INDArray from a CSC matrix
=> Add new examples for nd4j

dl4j-examples/src/main/java/org/deeplearning4j/examples/feedforward/anomalydetection/MNISTAnomalyExample.java
Converted unnecessary Triple to Pair and removed counter. Cleaned up documentation in few places.
=> Fix for MNISTAnomaly example contains redundant code #81

dl4j-examples/src/main/java/org/deeplearning4j/examples/recurrent/encdec/CorpusIterator.java, dl4j-examples/src/main/java/org/deeplearning4j/examples/recurrent/encdec/CorpusProcessor.java, dl4j-examples/src/main/java/org/deeplearning4j/examples/recurrent/encdec/EncoderDecoderLSTM.java, dl4j-examples/src/main/java/org/deeplearning4j/examples/recurrent/encdec/get_data.sh, dl4j-examples/src/main/java/org/deeplearning4j/examples/recurrent/encdec/gpu_monitor.sh
This is a seq2seq encoder-decoder LSTM model made according to the Google's paper: https://arxiv.org/abs/1506.05869
=> Add encoder-decoder LSTM example

.github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
Contributing refers to example-specific content.
=> Adds PR & Issue templates.

dl4j-examples/src/main/java/org/deeplearning4j/examples/convolution/LenetMnistExample.java
Made learning rate policy examples more clear. Users appear to be misusing the lr schedule API, so this will help make it more clear.
It's just commented-out code. Tested in pre-existing model.
=> Add a learning rate schedule example.

dl4j-examples/src/main/java/org/deeplearning4j/examples/recurrent/character/melodl4j/Midi2MelodyStrings.java, dl4j-examples/src/main/java/org/deeplearning4j/examples/recurrent/character/melodl4j/PlayMelodyStrings.java, dl4j-examples/src/main/java/org/deeplearning4j/examples/userInterface/GradientsListenerExample.java, dl4j-examples/src/main/java/org/deeplearning4j/examples/userInterface/util/GradientsViewer.java
=> Fix minor bug in playing melody strings (play last note).   Update documentation.

dl4j-examples/src/main/java/org/deeplearning4j/examples/convolution/AnimalsClassification.java
=> Update references link

dl4j-examples/src/main/java/org/deeplearning4j/examples/feedforward/mnist/MLPMnistTwoLayerExample.java
=> Fix logger invocation for MLPMnistTwoLayerExample

README.md
Fixes https://github.com/deeplearning4j/deeplearning4j/issues/2877
=> Document the javacpp.platform system property

dl4j-examples/src/main/java/org/deeplearning4j/examples/dataexamples/ImageDrawer.java
Refactor duplicate code in function.
move model inputs -0.5 to 0,5 from 0 to 1.
Add (optional) UIServer to allow monitoring of learning in browser.
Use RELU initiation and LeakyRelu activation to improve net performance.
Manually verified the example still runs,
=> Reduce duplicate code

dl4j-examples/src/main/java/org/deeplearning4j/examples/nlp/tsne/TSNEStandardExample.java, dl4j-examples/src/main/java/org/deeplearning4j/examples/userInterface/util/GradientsAndParamsViewer.java
If users click on a param name on the left, they'll see details about layer learning rate, momentum, activation function, and updater.   The details canNOT be updated.
Please review
=> If users click on a param name on the left, they'll see details about the layer.

datavec-examples/src/main/java/org/datavec/transform/basic/BasicDataVecExample.java, datavec-examples/src/main/java/org/datavec/transform/basic/PivotExample.java, datavec-examples/src/main/resources/BasicDataVecExample/PivotExampleData.csv
=> DataVec examples

datavec-examples/src/main/java/org/datavec/transform/basic/BasicDataVecExample.java, datavec-examples/src/main/java/org/datavec/transform/basic/PivotExample.java
=> Minor renaming + comments for datavec examples

dl4j-examples/src/main/java/org/deeplearning4j/examples/recurrent/regression/MultiTimestepRegressionExample.java, dl4j-examples/src/main/java/org/deeplearning4j/examples/recurrent/regression/SingleTimestepRegressionExample.java
Fixes bugs in MultiTimestepRegression chart. Fixes #439 
Cleans up code in both RNN Regression examples
Verified the examples still run correctly.
=> Code cleanup and bug fix.

dl4j-cuda-specific-examples/src/main/java/org/deeplearning4j/examples/multigpu/vgg16/dataHelpers/FeaturizedPreSave.java, dl4j-spark-examples/dl4j-spark/src/main/java/org/deeplearning4j/transferlearning/vgg16/dataHelpers/FeaturizedPreSave.java
Get rid of lombok declaration in presave. #457
IntelliJ code analysis and cleanup.
Manual test of main method.
=> Get rid of lombok declaration in presave.

dl4j-examples/src/main/java/org/deeplearning4j/examples/recurrent/encdec/CorpusProcessor.java, dl4j-examples/src/main/java/org/deeplearning4j/examples/recurrent/encdec/EncoderDecoderLSTM.java
Added Javadoc and reworked wordsToIndexes
`mvn compile`
=> Added more documentation and reduced complexity in one method

lstm-hdfs/pom.xml, pom.xml, rl4j-examples/pom.xml
Updates lstm-hdfs with best practices
Tests run
=> Align scala-plugin config with best practices

dl4j-examples/src/main/java/org/deeplearning4j/examples/misc/customlayers/CustomLayerExample.java, dl4j-examples/src/main/java/org/deeplearning4j/examples/misc/customlayers/layer/CustomLayerImpl.java, dl4j-examples/src/main/java/org/deeplearning4j/examples/recurrent/encdec/CorpusIterator.java, dl4j-examples/src/main/java/org/deeplearning4j/examples/recurrent/seq2seq/CustomSequenceIterator.java, dl4j-examples/src/main/java/org/deeplearning4j/examples/userInterface/util/GradientsAndParamsViewer.java
***DO NOT MERGE UNTIL DL4J PR IS MERGED***
Updates to match: https://github.com/deeplearning4j/deeplearning4j/pull/3653
=> Updates after recent DL4J refactoring/changes

dl4j-examples/src/main/java/org/deeplearning4j/examples/recurrent/basic/BasicRNNExample.java
Replace manual loop with ND4J IMax.
fix typos and smaller java items.
Example still runs. Output is a little cleaner.
=> Cleans up code.

dl4j-examples/src/main/java/org/deeplearning4j/examples/dataexamples/ImagePipelineExample.java, dl4j-examples/src/main/java/org/deeplearning4j/examples/misc/earlystopping/EarlyStoppingMNIST.java
Fixes: https://github.com/deeplearning4j/dl4j-examples/issues/231
Remove unused code.
code now passes IntelliJ 'Inspect Code'.
Example still runs.
=> ImagePipelineExample improvements.

lstm-hdfs/src/main/java/org/deeplearning4j/examples/MDSIterator.java
=> fix for get preprocessor

dl4j-cuda-specific-examples/src/main/java/org/deeplearning4j/examples/multigpu/GradientsSharingLenetMnistExample.java, dl4j-examples/pom.xml, dl4j-examples/src/main/java/org/deeplearning4j/examples/inference/ParallelInferenceExample.java
- new ParallelWrapper example, to show gradients sharing use
- ParallelInference example
=> R119 parallel examples

pom.xml, rl4j-examples/pom.xml, rl4j-examples/src/main/java/org/deeplearning4j/examples/rl4j/A3CALE.java, rl4j-examples/src/main/java/org/deeplearning4j/examples/rl4j/A3CCartpole.java, rl4j-examples/src/main/java/org/deeplearning4j/examples/rl4j/ALE.java, rl4j-examples/src/main/java/org/deeplearning4j/examples/rl4j/AsyncNStepCartpole.java, rl4j-examples/src/main/java/org/deeplearning4j/examples/rl4j/Cartpole.java, rl4j-examples/src/main/java/org/deeplearning4j/examples/rl4j/Toy.java
Updates for changes in the API of RL4J, plus new examples for ALE and A3CALE examples.
Build succeeds.
=> Update rl4j-examples and add examples for ALE

dl4j-examples/src/main/java/org/deeplearning4j/examples/misc/lossfunctions/GaussianMixtureIterator.java, dl4j-examples/src/main/java/org/deeplearning4j/examples/misc/lossfunctions/MixtureDensityNetwork.java
Based on this, with some tweaks:
https://github.com/deeplearning4j/dl4j-examples/pull/461
=> Mixture density network example

dl4j-examples/src/main/java/org/deeplearning4j/examples/nlp/paragraphvectors/ParagraphVectorsClassifierExample.java, dl4j-examples/src/main/java/org/deeplearning4j/examples/nlp/sequencevectors/SequenceVectorsTextExample.java, dl4j-examples/src/main/java/org/deeplearning4j/examples/nlp/tsne/TSNEStandardExample.java, dl4j-examples/src/main/java/org/deeplearning4j/examples/nlp/word2vec/Word2VecRawTextExample.java, dl4j-examples/src/main/java/org/deeplearning4j/examples/nlp/word2vec/Word2VecUptrainingExample.java, dl4j-examples/src/main/java/org/deeplearning4j/examples/recurrent/processnews/TrainNews.java
Fix a batch of deprecated code.
Made sure the examples still run
=> Fix a batch of deprecated code.

dl4j-examples/src/main/java/org/deeplearning4j/examples/convolution/AnimalsClassification.java, dl4j-examples/src/main/java/org/deeplearning4j/examples/feedforward/classification/detectgender/PredictGenderTrain.java, dl4j-examples/src/main/java/org/deeplearning4j/examples/feedforward/regression/RegressionMathFunctions.java, dl4j-examples/src/main/java/org/deeplearning4j/examples/misc/customlayers/CustomLayerExample.java, dl4j-examples/src/main/java/org/deeplearning4j/examples/recurrent/processnews/PrepareWordVector.java, dl4j-examples/src/main/java/org/deeplearning4j/examples/recurrent/processnews/TestNews.java
Updated the deprecated code for another 5 files.
The examples that ran correctly still run. (In this case one of them was broken: see #526 )
=> Fix a batch of depreceated code for #524.

datavec-examples/src/main/java/org/datavec/transform/basic/CustomReduceExample.java, datavec-examples/src/main/java/org/datavec/transform/basic/MultiOpReduceExample.java, dl4j-examples/src/main/java/org/deeplearning4j/examples/recurrent/encdec/CorpusIterator.java, dl4j-examples/src/main/java/org/deeplearning4j/examples/recurrent/seq2seq/CustomSequenceIterator.java, lstm-hdfs/src/main/java/org/deeplearning4j/examples/MDSIterator.java
see https://github.com/deeplearning4j/DataVec/pull/263
=> Examples of the new DataVec/Reducer API

dl4j-spark-cdh-examples/src/main/java/org/deeplearning4j/examples/SparkLSTMClinicalTimeSeriesClassificationExample.java, dl4j-spark-cdh-examples/src/main/java/org/deeplearning4j/examples/SparkLSTMClinicalTimeSeriesClassificationExampleHDFS.java, pom.xml
=> Changes to data pipeline for reduced memory - blog example

dl4j-examples/src/main/java/org/deeplearning4j/examples/convolution/sentenceclassification/CnnSentenceClassificationExample.java
The paper (https://arxiv.org/abs/1408.5882 which the model refers to) mentioned in section "2.1 Regularization" the use of "Dropout" in the penultimate layer which is missing in the code. It is added now and improves results.
Via training and testing the CNN.
=> Adding dropout Regularization

lstm-hdfs/pom.xml, pom.xml
Showing some error info, as follow the hyperlink:
https://github.com/deeplearning4j/dl4j-examples/issues/542
https://github.com/deeplearning4j/dl4j-examples/issues/543
=> somebody used the IDE that is eclipse ,so when the dl4j-example was imported the IDE that maybe show some error info

dl4j-spark-examples/dl4j-spark/src/main/java/org/deeplearning4j/mlp/MnistMLPDistributedExample.java, dl4j-spark-examples/dl4j-spark/src/main/java/org/deeplearning4j/mlp/MnistMLPExample.java
See known issues in release notes: https://deeplearning4j.org/releasenotes
=> Evaluation workaround for spark examples

dl4j-examples/pom.xml, dl4j-examples/src/main/java/org/deeplearning4j/examples/dataexamples/MnistImagePipelineExampleSave.java, dl4j-examples/src/main/java/org/deeplearning4j/examples/transferlearning/vgg16/EditAtBottleneckOthersFrozen.java, dl4j-examples/src/main/java/org/deeplearning4j/examples/transferlearning/vgg16/EditLastLayerOthersFrozen.java, dl4j-examples/src/main/java/org/deeplearning4j/examples/transferlearning/vgg16/FitFromFeaturized.java, dl4j-examples/src/main/java/org/deeplearning4j/examples/transferlearning/vgg16/dataHelpers/FeaturizedPreSave.java, dl4j-examples/src/main/java/org/deeplearning4j/examples/userInterface/util/GradientsAndParamsViewer.java, dl4j-examples/src/main/java/org/deeplearning4j/examples/userInterface/util/UIExampleUtils.java
Updates MinstIMagePipeline.
Removed deprecated code from Viewer.
Work in progress on #524
Munal test that Example still runs. Manual test of an example using the viewer to make sure it still runs.
=> Update / remove deprecated code.

dl4j-examples/src/main/java/org/deeplearning4j/examples/recurrent/basic/BasicRNNExample.java
Fix a couple of typos in `BasicRNNExample.java`
=> Fix typos.

dl4j-examples/src/main/java/org/deeplearning4j/examples/unsupervised/anomalydetection/ImageWithByteUtil.java, dl4j-examples/src/main/java/org/deeplearning4j/examples/unsupervised/anomalydetection/MnistLoader.java
Update the ImageWithByteUtil.java and the MnistLoader.java
=> Update the files

pom.xml
Switch back to native platform configuration on parent pom.
=> parent pom: back to nd4j native platform

dl4j-examples/src/main/java/org/deeplearning4j/examples/unsupervised/anomalydetection/AEMNISTAnomalyDectection.java
Updated the AEMNISTAnomalyDectection.java
=> Updated the AEMNISTAnomalyDectection.java

dl4j-cuda-specific-examples/src/main/java/org/deeplearning4j/examples/multigpu/GradientsSharingLenetMnistExample.java, dl4j-cuda-specific-examples/src/main/java/org/deeplearning4j/examples/multigpu/MultiGpuLenetMnistExample.java, dl4j-cuda-specific-examples/src/main/java/org/deeplearning4j/examples/multigpu/vgg16/MultiGpuLenetMnistExample.java, dl4j-examples/src/main/java/org/deeplearning4j/examples/convolution/Cifar.java, dl4j-examples/src/main/java/org/deeplearning4j/examples/misc/customlayers/CustomLayerExample.java, dl4j-examples/src/main/java/org/deeplearning4j/examples/nlp/tsne/TSNEStandardExample.java, dl4j-examples/src/main/java/org/deeplearning4j/examples/recurrent/seq2seq/AdditionRNN.java, nd4j-examples/src/main/java/org/nd4j/examples/numpy_cheatsheat/NumpyCheatSheat.java
Get rid of DataTypeUtil calls, using Nd4j.setDataType call instead
=> Nd4j.setDataType

dl4j-examples/src/main/java/org/deeplearning4j/examples/convolution/AnimalsClassification.java
Remove unused variable and import.
Resolves #623.
Verified example still works.
=> Get rid of hard coded numLabels and numExamples.

datavec-examples/src/main/java/org/datavec/transform/basic/BasicTransformExample.java
Adds a second simple datavec example demonstrating filters and String to categorical transform.
Tested manually.
=> Add Datavec example for the Iris dataset.

runexamples.sh
Small changes to add NaN and other checks on user input.
Manual script run.
=> [runexamples.sh] NaN check on user input

dl4j-examples/src/main/java/org/deeplearning4j/examples/dataexamples/MultiClassLogit.java, dl4j-examples/src/main/resources/logback.xml
Multiclass logistic regression example.
This is not a DNN but can be useful to introduce machine learning.
Manual test.
=> Multiclass Logit Example

dl4j-cuda-specific-examples/src/main/java/org/deeplearning4j/examples/multigpu/vgg16/MultiGpuVGG16TinyImageNetExample.java, dl4j-examples/build.gradle, dl4j-examples/src/main/kotlin/org/deeplearning4j/examples/feedforward/mnist/MLPMnistSingleLayerExample.kt, dl4j-examples/src/main/kotlin/org/deeplearning4j/examples/feedforward/mnist/MLPMnistTwoLayerExample.kt
Also the kotlin version was incremented to the current stable release. There should be no functional changes.
=> Migrated Kotlin examples to 1.0.0-alpha

dl4j-examples/src/main/java/org/deeplearning4j/examples/styletransfer/NeuralStyleTransfer.java
Fixes #659 cleans up all compiler warnings.
Verified example runs manually.
=> Fixes #659 cleans up all compiler warnings.

dl4j-spark-examples/dl4j-spark-cluster/pom.xml, dl4j-spark-examples/dl4j-spark-cluster/src/main/java/org/deeplearning4j/AnimalModelByHdfsCluster.java, dl4j-spark-examples/dl4j-spark-cluster/src/main/java/org/deeplearning4j/AnimalModelByHdfsSparkCluster.java, dl4j-spark-examples/dl4j-spark-cluster/src/main/java/org/deeplearning4j/datasets/DatasetIteratorFromHdfs.java, dl4j-spark-examples/dl4j-spark-cluster/src/main/java/org/deeplearning4j/datasets/DatasetReaderFromHdfs.java, dl4j-spark-examples/dl4j-spark-cluster/src/main/java/org/deeplearning4j/listeners/SparkScoreIterationListener.java, dl4j-spark-examples/dl4j-spark-cluster/src/main/java/org/deeplearning4j/utils/CommonUtils.java, dl4j-spark-examples/dl4j-spark-cluster/src/main/java/org/deeplearning4j/utils/ShowData2UIServer.java, dl4j-spark-examples/dl4j-spark-cluster/src/main/java/org/deeplearning4j/utils/ShowRemoteUIServer.java, dl4j-spark-examples/pom.xml
=> add example for spark & hadoop cluster

datavec-examples/pom.xml, dl4j-cuda-specific-examples/pom.xml, dl4j-examples/build.gradle, dl4j-examples/pom.xml, dl4j-spark-examples/dl4j-spark-cluster/pom.xml, dl4j-spark-examples/dl4j-spark-cluster/src/main/java/org/deeplearning4j/AnimalModelByHdfsSparkCluster.java, dl4j-spark-examples/dl4j-spark-cluster/src/main/java/org/deeplearning4j/datasets/DatasetReaderFromHdfs.java, dl4j-spark-examples/dl4j-spark-cluster/src/main/java/org/deeplearning4j/listeners/SparkScoreIterationListener.java, dl4j-spark-examples/dl4j-spark/pom.xml, dl4j-spark-examples/pom.xml, lstm-hdfs/pom.xml, nd4j-examples/pom.xml, nd4j-examples/src/main/java/org/nd4j/examples/CustomOpsExamples.java, pom.xml, rl4j-examples/pom.xml, standalone-sample-project/pom.xml
Some additional pom and API changes missed in the earlier update PR.
=> Additional post release updates

dl4j-examples/src/main/java/org/deeplearning4j/examples/convolution/AnimalsClassification.java
Minor changes were missed out in the previous pull requests which is added out here. 
Changed from `network.fit(trainIter,epochs);` to `network.fit(dataIter,epochs);` replacing deprecated usage of `MultipleEpochsIterator`.
Changed using loops through image transforms to an image pipeline.
Changed `batchSize` to `maxPathsPerLabel` to make it more understandable.
NN training and evaluation has been tested running without errors/Manually tested.
Please review
=> Update Animal classification example

dl4j-examples/src/main/java/org/deeplearning4j/examples/feedforward/classification/MLPClassifierLinear.java
just removed a duplicate call to weightInit()
=> remove duplicate weightInit() call

datavec-examples/src/main/java/org/datavec/inputsplit/Ex04_TransformSplitExample.java, datavec-examples/src/main/java/org/datavec/transform/basic/BasicDataVecExample.java, datavec-examples/src/main/java/org/datavec/transform/basic/BasicDataVecExampleLocal.java, datavec-examples/src/main/java/org/datavec/transform/basic/PivotExample.java, datavec-examples/src/main/java/org/datavec/transform/join/JoinExample.java
- fix some typos
- remove duplicated code
- change deprecated code
unit-tests
Please review
=> tiny clean up on dataVec examples

tf-import-examples/pom.xml, tf-import-examples/src/main/java/org/nd4j/examples/Boston.java, tf-import-examples/src/main/java/org/nd4j/examples/Imdb.java, tf-import-examples/src/main/java/org/nd4j/examples/Mnist.java, tf-import-examples/src/main/java/org/nd4j/examples/RunGraphExample.java
Adds graph runner example to tensorflow import directory.
Please review
=> Graph runner example

dl4j-examples/src/main/java/org/deeplearning4j/examples/modelimport/keras/DeepMojiAttentionLayer.java, dl4j-examples/src/main/java/org/deeplearning4j/examples/modelimport/keras/ImportDeepMoji.java, dl4j-examples/src/main/java/org/deeplearning4j/examples/modelimport/keras/KerasDeepMojiAttention.java
=> deepmoji example: custom samediff layer + keras model import

dl4j-examples/src/main/java/org/deeplearning4j/examples/convolution/alphagozero/AlphaGoZeroTrainer.java, dl4j-examples/src/main/java/org/deeplearning4j/examples/convolution/alphagozero/DL4JAlphaGoZeroBuilder.java, dl4j-examples/src/main/java/org/deeplearning4j/examples/convolution/alphagozero/DualResidualNetwork.java
Can only demonstrate training on dummy data, no tree search, no encoding of actual game positions, evaluation, scoring etc. Just the neural network training part for now.
=> Boiled-down AlphaGo Zero example

dl4j-examples/src/main/java/org/deeplearning4j/examples/dataexamples/ImagePipelineExample.java
there has some wrong with comment
dl4j is channel fisrt.
but  the comment is channel last
=> Update ImagePipelineExample.java Comment

tutorials/04. Feed-forward.zepp.ipynb
Fixing a grammar/wording issue in a sentence in the notebook example
The changed sentence was read again after the change, no new mistakes were found.
=> Fixes slight wording issue

dl4j-examples/src/main/java/org/deeplearning4j/examples/feedforward/mnist/MLPMnistSingleLayerExample.java, dl4j-examples/src/main/java/org/deeplearning4j/examples/feedforward/mnist/MLPMnistTwoLayerExample.java
No need to index. No need to specify sizes twice.
Manual test.
=> Update the layer builders in the configuration

dl4j-examples/src/main/java/org/deeplearning4j/examples/unsupervised/variational/VariationalAutoEncoderExample.java
Minor tuning change for VAE example
=> VAE LR fix

dl4j-examples/src/main/java/org/deeplearning4j/examples/convolution/mnist/MnistClassifier.java, dl4j-examples/src/main/java/org/deeplearning4j/examples/convolution/mnist/MnistClassifierUI.java
I think the MNIST example  is somethink like 'Hello World' in learning new programming leangauge, so I made some changes for better readbility and effective learning.
- Code cleanup
- Minor refactor
- Updated use deprecated API
- Add and update some comments
Running both examples after changes and compare with result from previous version.
=> Made some code cleanup and refactor for the mnist example

dl4j-examples/src/main/java/org/deeplearning4j/examples/dataexamples/BasicCSVClassifier.java
- Code cleanup
- Minor refactor
- Updated use deprecated API
- Added and updated some comments
Running both examples after changes and compare with result from previous version.
=> Made some code cleanup and refactor for the BasicCSVClassifier example

dl4j-examples/src/main/java/org/deeplearning4j/examples/feedforward/xor/XorExample.java
- Code cleanup
- Minor refactor
- Updated use deprecated API
- Added and updated some comments
Running both examples after changes and compare with result from previous version.
=> Made some code cleanup and refactor for the XOR example

dl4j-examples/src/main/java/org/deeplearning4j/examples/recurrent/processlottery/TrainLotteryModel.java
maybe fixed issue#847,  in this case, INDArray#.getRow(0) will cause "IllegalArgumentException: getRow() can be called on 2D arrays only", I debug it ,found this INDArray is not a 2D array. But I not very sure this solution。
just run it and it will not throw IllegalArgumentException again.
=> fix issue 847

dl4j-examples/src/main/java/org/deeplearning4j/examples/feedforward/xor/XorExample.java
changed initialization to account for API changes
.weightInit(new UniformDistribution(0, 1))
demo ran fine
Please review
=> Example was crashing until these modifications were made

.gitignore, android/.gitignore, android/DL4JImageRecognitionDemo/.gitignore, android/DL4JImageRecognitionDemo/app/.gitignore, android/DL4JImageRecognitionDemo/app/proguard-rules.pro, android/DL4JIrisClassifierDemo/.gitignore, android/DL4JIrisClassifierDemo/app/.gitignore, android/DL4JIrisClassifierDemo/app/proguard-rules.pro, android/DL4JModelTester/.gitignore, android/DL4JModelTester/proguard-rules.pro, dl4j-examples/.gitignore, dl4j-examples/build.gradle, dl4j-examples/src/main/java/org/deeplearning4j/examples/recurrent/encdec/get_data.sh, dl4j-examples/src/main/java/org/deeplearning4j/examples/recurrent/encdec/gpu_monitor.sh, dl4j-examples/src/main/kotlin/org/deeplearning4j/examples/feedforward/mnist/MLPMnistSingleLayerExample.kt, dl4j-examples/src/main/kotlin/org/deeplearning4j/examples/feedforward/mnist/MLPMnistTwoLayerExample.kt, dl4j-examples/src/main/resources/dropwizard.yml, dl4j-spark-examples/dl4j-spark/scripts/patentExamplePreproc.sh, dl4j-spark-examples/dl4j-spark/scripts/patentExampleTrain.sh, dl4j-spark-examples/dl4j-spark/scripts/tinyImagenetTrain.sh, rl4j-examples/vizdoom-instructions, tutorials/Dockerfile
Update copyright headers for rest of the source files
No tests were run.
Please review
=> Update copyright headers for rest of the source files

nd4j-examples/src/main/java/org/nd4j/examples/ConcatVstackHstackPad.java, nd4j-examples/src/main/java/org/nd4j/examples/CustomOpsExamples.java, nd4j-examples/src/main/java/org/nd4j/examples/Nd4jEx10_ElementWiseOperation.java, nd4j-examples/src/main/java/org/nd4j/examples/Nd4jEx11_Axpy.java, nd4j-examples/src/main/java/org/nd4j/examples/Nd4jEx12_INDArrayFromCSCMatrix.java, nd4j-examples/src/main/java/org/nd4j/examples/Nd4jEx13_LargeMatrices.java, nd4j-examples/src/main/java/org/nd4j/examples/Nd4jEx14_Normalizers.java, nd4j-examples/src/main/java/org/nd4j/examples/Nd4jEx15_Workspaces.java, nd4j-examples/src/main/java/org/nd4j/examples/Nd4jEx1_INDArrayBasics.java, nd4j-examples/src/main/java/org/nd4j/examples/Nd4jEx2_CreatingINDArrays.java, nd4j-examples/src/main/java/org/nd4j/examples/Nd4jEx3_GettingAndSettingSubsets.java, nd4j-examples/src/main/java/org/nd4j/examples/Nd4jEx4_Ops.java, nd4j-examples/src/main/java/org/nd4j/examples/Nd4jEx5_Accumulations.java, nd4j-examples/src/main/java/org/nd4j/examples/Nd4jEx6_BooleanIndexing.java, nd4j-examples/src/main/java/org/nd4j/examples/Nd4jEx7_MatrixOperation.java, nd4j-examples/src/main/java/org/nd4j/examples/Nd4jEx8_ReshapeOperation.java, nd4j-examples/src/main/java/org/nd4j/examples/Nd4jEx9_Functions.java
What changes were proposed in this pull request?
All compiler warnings in the nd4j examples fixed. 
Manual test. Issue raised for hstack issue in nd4j.
=> fix compiler warnings in nd4j examples.

dl4j-examples/src/main/java/org/deeplearning4j/examples/modelimport/tensorflow/LoadTensorFlowMNISTMLP.java
Signed-off-by: eraly <susan.eraly@gmail.com>
Minor path fix
By running example
Please review
=> path fix in TF import example

dl4j-examples/src/main/java/org/deeplearning4j/examples/feedforward/classification/detectgender/PredictGenderTest.java
The only change is to call setVisible() after all GUI components are initialized.  Otherwise, a mouse over is needed to fully render the user interface components.
I manually tested this locally from my development environtment.  With this change, all GUI components are visible at application start.
=> set the GUI visible after all components are initialized

dl4j-examples/src/main/java/org/deeplearning4j/examples/utilities/DataUtilities.java
Proxy support for `DataUtilities`. After applying my patch, `DataUtilities` in DL4J-examples can access to MNIST dataset via proxy server with JVM proxy options, such like `-Dhttp.proxyHost=...`.
I only tested manually by using `runexamples.sh` with the JVM options:
```
$NOOP java -Dhttp.proxyHost=proxyhost -Dhttp.proxyPort=88 -Dhttp.proxyUser=proxyuser -Dhttp.proxyPassword=password -cp ./dl4j-examples/target/dl4j-examples-*-bin.jar "$1"
```
and with the JVM options:
```
$NOOP java -Dhttp.proxyHost=noauth-proxyhost -Dhttp.proxyPort=88 -cp ./dl4j-examples/target/dl4j-examples-*-bin.jar "$1"
```
=> Proxy support for DataUtilities #929

dl4j-examples/src/main/java/org/deeplearning4j/examples/modelimport/tensorflow/BertInferenceExample.java, shared-utilities/src/main/java/org/deeplearning4j/examples/download/DownloaderUtility.java
=> bert inference on fine tuned TF model

dl4j-examples/src/main/kotlin/org/deeplearning4j/examples/feedforward/mnist/MLPMnistTwoLayerExample.kt
Just cleaning up the code. Also my trial of collaboration before I invest more time in more substantial changes :)
=> optimize imports, cleanup code

dl4j-examples/src/main/java/org/deeplearning4j/examples/advanced/modelling/densenet/DenseNetMain.java, dl4j-examples/src/main/java/org/deeplearning4j/examples/advanced/modelling/densenet/model/DenseNetBuilder.java, dl4j-examples/src/main/java/org/deeplearning4j/examples/advanced/modelling/densenet/model/DenseNetModel.java
This example was contributed by me, but I noticed few problems in architecture. Now I fixed connection between some layers.
Please review
=> Fixed DenseNet model

.gitignore
Signed-off-by: Dariusz Zbyrad <dariusz.zbyrad@gmail.com>
Removed duplicated patterns in the .gitignore file
Tried add files with excluded patterns
Please review
=> Removed duplicated pattern in the .gitignore file

arbiter-examples/pom.xml, cuda-specific-examples/pom.xml, dl4j-distributed-training-examples/pom.xml, dl4j-examples/pom.xml, dl4j-examples/src/main/java/org/deeplearning4j/examples/advanced/modelling/densenet/model/DenseNetBuilder.java, dl4j-examples/src/main/java/org/deeplearning4j/examples/advanced/modelling/densenet/model/DenseNetModel.java, mvn-project-template/pom.xml, nd4j-ndarray-examples/pom.xml, rl4j-examples/pom.xml, samediff-examples/pom.xml, tensorflow-keras-import-examples/pom.xml
=> Fix compilation errors/encoding issues

.github/actions/download-dl4j-test-resources-linux/action.yml, .github/actions/download-dl4j-test-resources-windows/action.yml, .github/actions/install-arm-cross-compile/action.yml, .github/actions/install-cmake-linux/action.yml, .github/actions/install-protobuf-linux/action.yml, .github/actions/msys2-base-setup/action.yml, .github/actions/publish-gh-packages/action.yml, .github/actions/update-deps-linux/action.yml, .github/workflows/example-sanity-check.yml
Adds actions to enable running workflow
Please review
=> Add actions

data-pipeline-examples/pom.xml, data-pipeline-examples/src/main/java/org/deeplearning4j/datapipelineexamples/tablesaw/TablesawCSVExample.java
Add tablesaw csv example
Please review
=> Add table saw example

data-pipeline-examples/pom.xml, dl4j-distributed-training-examples/pom.xml, dl4j-examples/pom.xml, dl4j-examples/src/main/java/org/deeplearning4j/examples/advanced/modelling/charmodelling/generatetext/GenerateTxtModel.java, dl4j-examples/src/main/java/org/deeplearning4j/examples/advanced/modelling/objectdetection/TinyYoloHouseNumberDetection.java, mvn-project-template/pom.xml, nd4j-ndarray-examples/pom.xml, onnx-import-examples/pom.xml, samediff-examples/pom.xml, tensorflow-keras-import-examples/pom.xml, tensorflow-keras-import-examples/src/main/java/org/deeplearning4j/modelimportexamples/tf/advanced/mobilenet/ImportMobileNetExample.java, tensorflow-keras-import-examples/src/main/java/org/deeplearning4j/modelimportexamples/util/BaseLabels.java, tensorflow-keras-import-examples/src/main/java/org/deeplearning4j/modelimportexamples/util/ClassPrediction.java, tensorflow-keras-import-examples/src/main/java/org/deeplearning4j/modelimportexamples/util/Labels.java, tensorflow-keras-import-examples/src/main/java/org/deeplearning4j/modelimportexamples/util/darknet/COCOLabels.java, tensorflow-keras-import-examples/src/main/java/org/deeplearning4j/modelimportexamples/util/darknet/DarknetLabels.java, tensorflow-keras-import-examples/src/main/java/org/deeplearning4j/modelimportexamples/util/darknet/VOCLabels.java, tensorflow-keras-import-examples/src/main/java/org/deeplearning4j/modelimportexamples/util/imagenet/ImageNetLabels.java
Updates examples for 1.0.0-M2.1
Please review
=> Update for release 1.0.0-M2.1
